name: 'merge-main'
description: 'merge changes to main'
inputs:
  bd-output:  # id of input
    description: 'branch deploy output'
    required: true
    default: 'false'
  target-env:  # id of input
    description: 'temporary branch name'
    required: true

runs:
  using: 'composite'
  steps:
      - name: temp branch commit
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ inputs.bd-output == 'true' }}
        id: commit
        with:
          branch: "${{inputs.target-env}}-merge-temp"
          create_branch: true
          commit_message: "[skip ci] branch-deploy lock/deploy ${{inputs.target-env}}"
          file_pattern: '*/applications/*/kustomization.yaml'

      - name: Report status check
        if: ${{ inputs.bd-output == 'true'  && steps.commit.outputs.commit_hash != '' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_checks = "${{ vars.GIT_STATUS_CHECKS }}".split(",")
            for (pr_check of pr_checks) {
            console.log(pr_check);
            github.checks.create({
              name: pr_check,
              head_sha: '${{ steps.commit.outputs.commit_hash }}',
              status: 'completed',
              conclusion: 'success',
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            }


      - name: temp branch merge
        shell: bash
        if: ${{ inputs.bd-output == 'true'  && steps.commit.outputs.commit_hash != '' }}
        run: |
          git config --global user.name 'Saurabh Ghodki'
          git config --global user.email 'saurabh.ghodki91@gmail.com'
          git remote set-url --push origin https://Ghodkis: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@github.com/GhodkiS/gilaactions
          git checkout main
          git pull
          git reset --hard  "${{steps.validate-environment.outputs.GITHUB_TARGET_ENV}}-merge-temp"
          git push

      
      - name: cleanup temp branch
        shell: bash
        if: ${{ inputs.bd-output == 'true'  && steps.commit.outputs.commit_hash != '' }}
        run: ./.github/scripts/branch-deploy.sh -a "cleanup"
        env:
          T_ENV_APP: ${{inputs.target-env}}