name: branch-deploy

on:
  issue_comment:
    types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: # only run on pull request comments and very specific comment body string as defined in our branch-deploy settings
      ${{ github.event.issue.pull_request &&
      (contains(github.event.comment.body, '.deploy') ||
      contains(github.event.comment.body, '.unlock')  ||
      (contains(github.event.comment.body, '.lock') && contains(github.event.comment.body, '--info')))  }}
     
    steps:
      # The branch-deploy Action
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v8.0.0
        with:
          environment_targets: 'app1_dev,app2_dev,app1_qa,app2_qa'
          trigger: '.deploy'
          disable_naked_commands: "true" 
          sticky_locks: "true"

        # If the branch-deploy Action was triggered, checkout our branch
      - uses: actions/checkout@v3
        with:
          ref: main
      # - uses: actions/cache/restore@v3
      #   id: cache
      #   with:
      #     path: temp-branch-cache-${{steps.branch-deploy.outputs.ref}}
      #     key: temp-branch-cache-${{steps.branch-deploy.outputs.ref}}
      - name: update target revision
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && (contains(github.event.comment.body, '.deploy') }}
        run: |
          t_env_app="${{steps.branch-deploy.outputs.environment}}"
          t_app=$(echo "$t_env_app" | awk -F '_' '{print $1}')
          t_env=$(echo "$t_env_app" | awk -F '_' '{print $2}')
          file="./$t_env/$t_app/kustomize.yaml"
          multiline_text=$(cat <<EOF
          # lock target environment starts
          - target:
              kind: Application
              name: $t_app
            patch: |-
               - op: replace
                 path: /spec/source/targetRevision
                 value: ${{steps.branch-deploy.outputs.ref}}
          # lock target environment ends
          EOF
          )
          echo "$multiline_text" >> "$file"
          git config --global user.name 'test-user'
          git config --global user.email 'saurabh.ghodki91@gmail.com'
          git add ./$t_env/$t_app/kustomize.yaml
          git commit -am "update target revision of ${{steps.branch-deploy.outputs.environment}} to ${{steps.branch-deploy.outputs.ref}}"
          git push
          
      - uses: actions/checkout@v3
        with:
          ref: ${{steps.branch-deploy.outputs.environment}}-branch-deploy-lock
          
      - name: update bd-lock
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && (contains(github.event.comment.body, '.deploy') }}
        run: |
          #echo ${{steps.branch-deploy.outputs.ref}} > bd-lock.json
          json_file="lock.json"
          key_to_update="branch"
          new_value=${{steps.branch-deploy.outputs.ref}}
          json_content=$(cat "$json_file")
          updated_json=$(echo "$json_content" | jq --arg key "$key_to_update" --arg value "$new_value" '.[$key] = $value')
          echo "$updated_json" > "$json_file"
          git config --global user.name 'test-user'
          git config --global user.email 'tech.user@company.com'
          git add "$json_file"
          git commit -am "update branch target"
          git push

      - name: update bd-lock
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && (contains(github.event.comment.body, '.unlock') }}
        run: |
          t_env_app="${{steps.branch-unlock.outputs.environment}}"
          t_app=$(echo "$t_env_app" | awk -F '_' '{print $1}')
          t_env=$(echo "$t_env_app" | awk -F '_' '{print $2}')
          file="./$t_env/$t_app/kustomize.yaml"
          sed -i '/# lock target environment starts/,/# lock target environment ends/d' $file
          git config --global user.name 'test-user'
          git config --global user.email 'saurabh.ghodki91@gmail.com'
          git add ./$t_env/$t_app/kustomize.yaml
          git commit -am "unlock ${{steps.branch-unlock.outputs.environment}}"
          git push