---
name: CICD

on:  # quoted so it is not considered a boolean
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  my-action:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - name: merge-run
      run: |
        echo "run during merge"