name: branch-deploy-release-lock

'on':
  pull_request:
    branches: 
      - main
    types: [ opened, reopened, synchronize ]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  status-check-temp:
      runs-on: ubuntu-latest
      steps:
      - name: checkout to main
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: status-check-temp
        run: |
          if [[ -f "./pr-fail" ]]; then
          exit 1
          fi
      
      - name: status-check-temp2
        run: |
          if [[ -f "./pr-fail" ]]; then
          exit 1
          fi


